import React from "react";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata = {
  title: "Terms & Conditions | PencilHub Studio",
  description: "Read the rules of engagement, visual intellectual property laws, and client terms of service for working with PencilHub.",
};

export default function TermsPage() {
  return (
    <div className="bg-background text-foreground pb-20">
      
      {/* Hero Header */}
      <section className="relative py-20 bg-neutral-gray border-b border-card-border overflow-hidden">
        <div className="absolute inset-0 bg-grid-overlay opacity-15 pointer-events-none" />
        <div className="max-w-3xl mx-auto px-6 pt-10 relative z-10">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-foreground/60 hover:text-accent-blue transition-colors group mb-6"
          >
            <ArrowLeft className="w-4 h-4 transition-transform group-hover:-translate-x-0.5" />
            Back to Home
          </Link>
          <span className="text-xs uppercase tracking-widest font-bold text-accent-blue font-mono">Legal Guidelines</span>
          <h1 className="font-display text-4xl sm:text-5xl font-extrabold tracking-tight text-foreground mt-4 leading-none">
            Terms & Conditions
          </h1>
          <p className="text-xs text-foreground/45 font-mono mt-3">Last updated: July 29, 2026</p>
        </div>
      </section>

      {/* Main Content */}
      <article className="max-w-3xl mx-auto px-6 py-16 prose prose-zinc dark:prose-invert">
        <p className="text-sm sm:text-base text-foreground/75 leading-relaxed">
          Welcome to PencilHub! These terms and conditions outline the rules and regulations for the use of PencilHub's Website, located at pencilhub.in. By accessing this website, we assume you accept these terms and conditions.
        </p>

        <h2 className="font-display text-xl sm:text-2xl font-extrabold text-foreground mt-8 mb-4">1. Intellectual Property</h2>
        <p className="text-sm sm:text-base text-foreground/75 leading-relaxed">
          Unless otherwise stated, PencilHub and/or its licensors own the intellectual property rights for all material on PencilHub. All intellectual property rights are reserved. You may access this from PencilHub for your own personal use subjected to restrictions set in these terms and conditions.
        </p>
        <p className="text-sm sm:text-base text-foreground/75 leading-relaxed">
          You must not:
        </p>
        <ul className="flex flex-col gap-2.5 my-4 pl-5 list-disc text-foreground/75 text-sm sm:text-base leading-relaxed">
          <li>Republish visual assets, logo renders, or layouts from PencilHub.</li>
          <li>Sell, rent, or sub-license brand assets generated by the studio without clearing contract schedules.</li>
          <li>Reproduce, duplicate, or copy code templates from this Next.js app.</li>
          <li>Redistribute content from PencilHub without credits.</li>
        </ul>

        <h2 className="font-display text-xl sm:text-2xl font-extrabold text-foreground mt-8 mb-4">2. Creative Project Engagements</h2>
        <p className="text-sm sm:text-base text-foreground/75 leading-relaxed">
          All client quotes, brand audits, design deliverables, and timeline milestones are subject to individual contract briefs signed by both parties. Direct client onboarding is managed securely via email correspondence on <a href="mailto:pencilhubsocial@gmail.com" className="text-accent-blue font-bold">pencilhubsocial@gmail.com</a>.
        </p>

        <h2 className="font-display text-xl sm:text-2xl font-extrabold text-foreground mt-8 mb-4">3. Governing Law</h2>
        <p className="text-sm sm:text-base text-foreground/75 leading-relaxed">
          These Terms shall be governed by and defined in accordance with the laws of India. PencilHub and yourself consent that the courts of Bangalore shall have exclusive jurisdiction to resolve any dispute which may arise under these terms.
        </p>

        <h2 className="font-display text-xl sm:text-2xl font-extrabold text-foreground mt-8 mb-4">4. Liability Limitations</h2>
        <p className="text-sm sm:text-base text-foreground/75 leading-relaxed">
          PencilHub makes no representations or warranties, of any kind related to this website or the materials contained on this website. Also, nothing contained on this website shall be interpreted as advising you.
        </p>
      </article>

    </div>
  );
}
